/**
 * Writes PuzzleGetawayTests/SortGoldenData.swift: forge-generated golden traces for the Swift rules tests.
 * For a handful of bundled levels (plain, hidden, lock, capped, rusty) it records a seeded random walk
 * (legal moves only, including "pointless" ones) with the fingerprint, legal-move count and solved flag after
 * every step, plus the forge's optimal solution length where the A* proves it.
 * Usage: npm run gen:sort-golden
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { DEFAULT_RESOURCES } from "../src/validate.js";
import type { LevelEnvelope, LevelFile } from "../src/schema.js";
import { SortRules, fingerprint, type SortPayload } from "../src/modes/sortcore.js";
import { solveFrom } from "../src/solvers/sortSolver.js";
import { createRng } from "../src/util/prng.js";

const wanted: [string, string][] = [
  ["d1-liquid.json", "d1-liquid-01"],
  ["d1-liquid.json", "d1-liquid-05"],
  ["d1-liquid.json", "d1-liquid-13"],
  ["d1-liquid.json", "d1-liquid-18"],
  ["d1-liquid.json", "d1-liquid-21"],
  ["d1-bolt.json", "d1-bolt-19"],
  ["d2-bolt.json", "d2-bolt-02"],
  ["d2-bolt.json", "d2-bolt-04"],
  ["d2-bolt.json", "d2-bolt-05"],
];

interface Golden {
  name: string;
  payload: SortPayload;
  initialFp: string;
  initialLegal: number;
  optimal: number;
  steps: { move: [number, number]; fp: string; legal: number; solved: boolean }[];
}

const out: Golden[] = [];
wanted.forEach(([file, id], idx) => {
  const lf = JSON.parse(readFileSync(join(DEFAULT_RESOURCES, "Levels", file), "utf8")) as LevelFile;
  const level = lf.levels.find((l: LevelEnvelope) => l.id === id) as LevelEnvelope;
  const payload = level.payload as SortPayload;
  const rules = new SortRules(payload);
  let s = SortRules.initialState(payload);
  const g: Golden = { name: id, payload, initialFp: fingerprint(s), initialLegal: rules.legalMoves(s).length, optimal: -1, steps: [] };
  const exact = solveFrom(rules, s, { weight: 1, budget: 150_000 });
  if (exact.solution) g.optimal = exact.solution.length;
  const rng = createRng(777 + idx);
  for (let i = 0; i < 12; i++) {
    const moves = rules.legalMoves(s);
    if (moves.length === 0 || rules.isSolved(s)) break;
    const m = rng.pick(moves);
    s = rules.apply(m, s) as ReturnType<typeof SortRules.initialState>;
    g.steps.push({ move: [m.from, m.to], fp: fingerprint(s), legal: rules.legalMoves(s).length, solved: rules.isSolved(s) });
  }
  // Then follow a solver path to the end so each trace also covers lock openings, rust clearing and the solved state.
  const rest = solveFrom(rules, s, { weight: 2, budget: 200_000 }).solution ?? [];
  for (const m of rest) {
    s = rules.apply(m, s) as ReturnType<typeof SortRules.initialState>;
    g.steps.push({ move: [m.from, m.to], fp: fingerprint(s), legal: rules.legalMoves(s).length, solved: rules.isSolved(s) });
  }
  out.push(g);
});

const json = JSON.stringify(out);
const swift = `// GENERATED by tools/forge/scripts/gen-sort-golden.ts (npm run gen:sort-golden). Do not edit by hand.
// Golden traces produced by the forge's rules implementation; SortRulesTests replays them through the Swift rules.
enum SortGoldenData {
    static let json = #"""
${json}
"""#
}
`;
const target = resolve(DEFAULT_RESOURCES, "../../PuzzleGetawayTests/SortGoldenData.swift");
writeFileSync(target, swift);
console.log(`wrote ${target} (${out.length} traces, ${out.reduce((n, g) => n + g.steps.length, 0)} steps)`);
