/**
 * Hand-authored original pixel scenes for Pixel Picnic (Critter Clear), Station Snack Cart.
 * Palette ids (Art/palette.json): r tomato, o tangerine, y sunbeam, g meadow, t lagoon, b sky,
 * i twilight, p plum, k blossom, n cocoa, w cloud, s slate.  '.' = transparent (cleared from the start),
 * '#' = stone blocker (crumbles once something adjacent is packed).
 */
export interface Scene {
  id: string;
  title: string;
  rows: string[];
}

export const SCENES: Scene[] = [
  {
    id: "fruit-cup",
    title: "Fruit Cup",
    rows: [
      "....g.....",
      "...gg.g...",
      "..rrgrrg..",
      ".rrrrrrrr.",
      ".rrwrrrwr.",
      "wwwwwwwwww",
      ".wwwwwwww.",
      "..wwwwww..",
      "....ww....",
      "..wwwwww..",
    ],
  },
  {
    id: "tea-tray",
    title: "Tea Tray",
    rows: [
      "............w..",
      "...........w...",
      ".....y......w..",
      "k...kkk........",
      "kk.kkkkk.kkyyy.",
      ".kkwkkkkk.kwwww",
      "..kwkkkkk.kwwww",
      "...kkkkk.kk.w..",
      ".nnnnnnnnnnnnn.",
      "nnnynynynynynnn",
      "nnnnnnnnnnnnnnn",
      "..nnnnnnnnnnn..",
    ],
  },
  {
    id: "donut-box",
    title: "Donut Box",
    rows: [
      "bbbbbbbbbbbbb",
      "bwooowwwooowb",
      "bowkkowonnwob",
      "bokwkowonwnob",
      "bokkwowonnnob",
      "bwooowwwooowb",
      "bwwwwwwwwwwwb",
      "bwooowwwooowb",
      "bowwwowokkwob",
      "bowwwowokwkob",
      "bowwwowowkkob",
      "bwooowwwooowb",
      "bbbbbbbbbbbbb",
    ],
  },
  {
    id: "sandwich",
    title: "Sandwich",
    rows: [
      ".nnnnnnnnnnnn.",
      "noooooooooooon",
      "noooooooooooon",
      "noooooooooooon",
      "nggggggggggggn",
      "nggoggoggoggon",
      "noooooooooooon",
      "nrrrrrrrrrrrrn",
      "nrrrorrrrorrrn",
      "nyyyyyyyyyyyyn",
      "nnyynnnnyynnnn",
      "noooooooooooon",
      "noooooooooooon",
      ".nnnnnnnnnnnn.",
    ],
  },
  {
    id: "ramen-bowl",
    title: "Ramen Bowl",
    rows: [
      "....w.....w...",
      ".....w...w....",
      "....w.....w...",
      "...iiiiiiii...",
      ".iiwwwygookki.",
      "iowwywyyykkkki",
      "ioowwyyygokkoi",
      ".iigoogoogoii.",
      ".iiiiiiiiiiii.",
      ".iiwiwiwiwiwi.",
      "..wiwiwiwiwi..",
      "...iiiiiiii...",
      ".....iiii.....",
      "....iiiiii....",
    ],
  },
  {
    id: "strawberry-tart",
    title: "Strawberry Tart",
    rows: [
      "........g.......",
      ".......gg.......",
      "......gg.g......",
      "...g..rrrb..g...",
      "...ggrwwwwrgg...",
      "...rwwwwwwwwr...",
      "..rwwwrwwwwwwb..",
      "..rwwwwwwrwwwr..",
      "..rwwwwwwwwwwr..",
      ".rwwrwwrwwwrwwr.",
      ".rwwwwwwwwwwwwr.",
      "oyyyyyyyyyyyyyyo",
      "oyyyyyyyyyyyyyyo",
      "oooooooooooooooo",
      ".oooooooooooooo.",
      ".oooooooooooooo.",
    ],
  },
  {
    id: "pretzel-stand",
    title: "Pretzel Stand",
    rows: [
      "rrwwrrwwrrwwrrwwrr",
      "rrwwrrwwrrwwrrwwrr",
      "rrwwrrwwrrwwrrwwrr",
      "rrwwrrwwrrwwrrwwrr",
      "n..oooo....#ooo..n",
      "n.oyooyo..oy#oyo.n",
      "noyo..oyo#yo..oyon",
      "noo....oyyo....#on",
      "noo....oyyo....oon",
      "noyo..#yooyo..oyon",
      "n.oy#oyo..oyooyo.n",
      "n..#yyo....oyoo..n",
      "n...oo.#ooooo.oo.n",
      "nnnnnnnnnnnnnnnnnn",
      "tttttttttttttttttt",
      "tttttttttttttttttt",
    ],
  },
  {
    id: "onigiri-bento",
    title: "Onigiri Bento",
    rows: [
      "pppppppppppppppppp",
      "pkkkkkkkkpkkkkkkkp",
      "pkkkkkkkkpkyyyyykp",
      "pkkkkwwkkpkyywyykp",
      "pkkkwwwwkpkyyyyykp",
      "pkkkwwwwkpkyyyyykp",
      "pkkwwrrwwpkyywyykp",
      "pkkwwwwwwpkyyyyykp",
      "pkwwwwwwwwkkkkkkkp",
      "pkwwsssswwpppppppp",
      "pksssssssskkkkkkkp",
      "pkkkkwwkkpkkgkkkkp",
      "pkkkwwwwkpkgggkkkp",
      "pkkwwwwwwpkgggggkp",
      "pkkwwwwwwpkkgrgggp",
      "pkwwwwwwwwkkrrrgkp",
      "pkwwwwwwwwkkkrkkkp",
      "ppsssssssspppppppp",
    ],
  },
  {
    id: "lemonade-jug",
    title: "Lemonade Jug",
    rows: [
      ".....g.g..r.......",
      ".....ggg..w.......",
      "..b...g...r.......",
      "...bb.....wooo....",
      "...b.b....royo....",
      ".....bywyywooo....",
      ".....byyyyyyb.....",
      "...bbbbbbbbbbb....",
      "...byyyyyyyyybbbb.",
      "...bywwyyyywyb..b.",
      "...bywyoooywyb..b.",
      "...byyooyooyyb..b.",
      "...byyoyoyowwbbbb.",
      "...bywwoyoowwb....",
      "...bywwoooyyyb....",
      "...bbbbbbbbbbb....",
      "..ttttttttttttt...",
      ".ttttttttttttttt..",
    ],
  },
  {
    id: "snack-cart",
    title: "Snack Cart",
    rows: [
      "..........nyy.......",
      "..........n.........",
      ".rwwrrwwrrwwrrwwrrw.",
      ".rwwrrwwrrwwrrwwrrw.",
      ".rwwrrwwrrwwrrwwrrw.",
      ".rwwrrwwrrwwrrwwrrw.",
      "..wwrrwwrrwwrrwwrrww",
      "..niiyiiiiiiiiiiin..",
      "..niyyyiiiiiiigign..",
      "..niyyyiiwwirrgggn..",
      "..niyyyiiwwirrigin..",
      "..niiiiiiwwirriiin..",
      "..nnnnnnnnnnnnnnnn..",
      "nnnnnnnnnnnnnnnnnnnn",
      "nnnnnnnnnnnnnnnnnnnn",
      ".ttttttwwwwwwtttttt.",
      ".tttssswyyyywtssstt.",
      ".ttssssstttttssssst.",
      "...sswss.....sswss..",
      "....sss.......sss...",
    ],
  },
];

export const SCENE_BY_ID: Record<string, Scene> = Object.fromEntries(SCENES.map((s) => [s.id, s]));
